export const WEB3_LOADED = "WEB3_LOADED";
export const WALLET_ADDRESS_LOADED = "WALLET_ADDRESS_LOADED";

//Crowd funding
export const CROWD_FUNDING_CONTRACT_LOADED = "HOP DONG TAI THANH CONG";

// Project
export const PROJECT_CONTRACTS_LOADED = "DA TAI CAC DANH SACH DU AN";
export const PROJECTS_LOADED = "DANH SACH CAC DU AN DA DUOC TAI LEN";
export const NEW_PROJECT_CONTRACT_LOADED = "HOP DONG DU AN MOI DUOC TAI LEN";
export const NEW_PROJECT_LOADED = "DU AN MOI DA DUOC TAI";
export const INCREASE_PROGRESS = "TANG TIEN DO";
export const WITHDRAW_BALANCE = "RUT SO DU";